language: python
python:
  - "3.7"
before_install:
  - curl -sL https://sentry.io/get-cli/ | sudo bash
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - ./check.sh
  - echo $TEST_VARIABLE
  - sentry-cli releases new -p 'hello-sentry' "$(./print_release_version.py)"
  - sentry-cli releases set-commits --auto "$(./print_release_version.py)"
  - sentry-cli releases finalize "$(./print_release_version.py)"
env:
  - TEST_VARIABLE='foo'
