language: python
python:
  - "3.7"
before_install:
  - curl -sL https://sentry.io/get-cli/ | sudo bash
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - ./check.sh
  - echo $TEST_VARIABLE
  - echo $TEST_VARIABLE_2
  - echo $TEST_GLOBAL_VARIABLE
  - echo $TEST_GLOBAL_VARIABLE_2
  - echo $TEST_SECURE_GLOBAL_VARIABLE
  - sentry-cli releases new -p 'hello-sentry' "$(./print_release_version.py)"
  - sentry-cli releases set-commits --auto "$(./print_release_version.py)"
  - sentry-cli releases finalize "$(./print_release_version.py)"
env:
  global:
    - TEST_GLOBAL_VARIABLE='spam'
    - TEST_GLOBAL_VARIABLE_2='egg'
    - secure: GNmqez83X2WM8jtlf2U4ARBFwNCqSOtD0LpCsRRu8LVuL4f1EuBfIEzjX2edIkkuTALQb8gQhVy9zqQKdYc9D5MImOeJcwSDgN/WsTPGFPyGx1Yy7C4ZFuHniVAanaxi0DVmC69oTbnEGBdfyV4bdymw5/Rwj1Xw3s2GdX/BSofoZXV3qZjXldjw8P6b29D3yMW24VWwWIV4unX2XgZFMapv/5XA9dMgM9EXImyj3AIKxtvCifxzgKFSZl4779qk7P6xHAAdwnsinulU3/jHSSIx3CQEREXnms/6n1uRh2Dj3fT0LfQZfR6ipi2t2+BY1A2L0wNV2ifk12aKLNw9dziecpfrGIsO+Adf7fkNFt/6UUPMXMcyexUeFHB6x6hBcsevBb+GywSiSUEKHUV2tNqc9Hem72eoFc3uZ4w/oN1F5EYgE84Cek9i31MqyN4c2Bmsnww+0bb7bOnNSGk/UmLdTwJ3wIbM05ZQNwWCDTJOJL5jjMax0WnqL2n+X8vs/cNSeW+EGdm2QsCA4KTCSQYkOMu9Gqntm0uZtMxIClr7IAuP1c4uIoxVdnNGZItK+WRDwoXLKB5PdWoCD+c0eDNk9DXlLbOwwkJDcrFsqqizTEPhkxEQj8u+0jkkRcwNP1T9yx9JL0MIgIdEpUYmPQpqDon70C7fyyO3PIf91nQ=
  jobs:
    - TEST_VARIABLE='foo' TEST_VARIABLE_2='bar'
